#!/usr/bin/python3
# -*- coding: utf-8 -*-



class Child:
    def __init__(self):
        self.next = None # the pointer initially points to nothing

    def is_next_valid(self):
        return self.next != None;

    def next_child(self):
        return self.next;


def is_every_child_here(first_child):
@   @q1@@
