#!/usr/bin/python3
# -*- coding: utf-8 -*-


fibo = {}
fact = {}
sum_dic = {}

def n_sum(n):
    if n < 2:
        return n
    else:
        return n + memoization(n_sum, n-1)

@@q2@@

@@q3@@

mapping = {fibonacci: fibo, factorial: fact, n_sum: sum_dic}
@@q1@@
