#!/usr/bin/python3
# -*- coding: utf-8 -*-


def forbid_max(list):
    raise AttributeError(("Nice try! But 'max' has been disabled for list objects.\n"
                         "\t\tPlease write an actual returning the maximum of the list."))

max = forbid_max

@@q1@@
